version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"