# Run a container with both BlackLab Frontend and Server
version: '3.9'

services:

  frontend:
    image: instituutnederlandsetaal/blacklab-frontend:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: docker/frontend-bls.dockerfile
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    ports:
      - "8080:8080" # frontend and BLS will both be available on 8080
    volumes:
      # Default values have no effect, but user can override CORPUS_DIR/_NAME to bind mount corpus
      - ${CORPUS_DIR:-./README.md}:/data/index/${CORPUS_NAME:-README.md}

  frontend-proxy:
    profiles: [ "proxy" ] # don't start this by default
    image: instituutnederlandsetaal/blacklab-frontend-proxy:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: docker/frontend-proxy.dockerfile
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    ports:
      - "8080:8080" # frontend and BLS will both be available on 8080
