<style>
p.spacer { height: 1cm; }
p.endspacer { height: 5cm; }
.internal { display: none; }
</style>

<h1>ABOUT THE CORPUS HEDENDAAGS NEDERLANDS</h2>

<ul>
<li><a href='#intro'>Introduction</a></li>
<li><a href='#about'>Corpus data and metadata</a></li>
<li><a href='#help'>Help</a></li>
<li><a href='#beta'>Beta</a></li>
</ul>

<p class='spacer'><a name='intro'></a>&nbsp;</p>
<h2>INTRODUCTION</h2>
<p>Since 1994, <a href="http://www.inl.nl" target="_blank">The Instituut voor Nederlandse Lexicologie</a> has put online several corpora of contemporary Dutch: the 5, 27 and 38 million words corpora and the Dutch Parole Internet Corpus. The <i>Corpus Hedendaags Nederlands</i> in the current release is a first step towards a monitor corpus for contemporary Dutch. The material of the old corpora was integrated. For the first release (17 January 2014) a considerable amount of more recent material was added from two newspapers: <i>NRC Handelsblad</i> and <i>De Standaard</i> (until June 2013). For the second release (June 2014) more material from these two sources has been added from July 2013 - December 2013, as has other sources from Suriname and the Netherlands Antilles, such as newspapers, material published on internet (blog, website) and books written by Surinam authors.</p>

<p>The software powering this website was developed at the INL with support from the <a href="http://www.taalunieversum.org" target="_blank">Dutch Language Union and the <a href="http://www.digitisation.eu">IMPACT</a> and <a href="http://www.clarin.nl">CLARIN</a> projects. The corpus search is powered by <a href="https://github.com/INL/BlackLab" target="_blank">BlackLab</a>, an open source Lucene-based corpus retrieval engine allowing fast and complex searches on large volumes of annotated text.</p>
<p>This website is optimized for the latest versions of <a href="https://www.google.com/intl/en/chrome/browser/" target="_blank">Google Chrome</a> and <a href="http://www.mozilla.org/en-US/firefox/new/" target="_blank">Mozilla Firefox</a>; using either of these browsers is recommended. Microsoft Internet Explorer is supported from version 9 and upwards.<p>

<p>Both data and application are in <a href='#beta'>beta</a> version. Comments are welcome, please send an email to the <a href="mailto:servicedesk@inl.nl">INL service desk</a>.</p>


<p class='spacer'><a name='about'></a>&nbsp;</p>
<h2>CORPUS DATA AND METADATA</h2>

<h3>Description of included source material</h2>

<p>The first release of the CHN included material from the following sources:</p>

<p class='internal'><b><u>Also available on chn.inl.nl</u></b></p>
<p><b>Legal Corpus </b>(1814-2000)</p>

<p>A collection of 5.856 texts that was available from the 80’s to 
1992 as <i>NLEX</i>, a legal text database. The material has been made
available by the Erasmus University. Documents in the French language and
undated documents have not been included in the corpus.</p>

<p><b>Political documents</b></p>

<ul>
<li>Staatsblad (law gazette) van het
Koninkrijk der Nederlanden (1991)
</li>
<li>
Troonredes (Queen’s speeches)
(1970-1988)
</li>
<li>
Proceedings of plenary parliamentary
meetings (1995)</li>
</ul>

<p><b>Newspapers</b></p>

<ul>
<li>
NRC Handelsblad (1990-2013); De Standaard (1995,
2003-2013); Meppeler Courant (1993-1996)</li>

<li>
Collection <i>van der Veen</i>: Material sampled from
from diverse newspapers (1983-1990)</li>

<li>
Quotation collection <i>Noord</i>: from
Bloembollenkrant (1986-1987), Bollenstreek (1987), De Echo (1986), De
Leidenaar (1986-1987), De Leidse Post (1986-1987), De Stem van Dordt
(1987), De Telegraaf (1986, 1987, 1988), De Volkskrant (1986-1988), De Waarheid
(1986-1988), De Warmonder (1986-1989), De Warmonder Courant (1989), Grens en
Maas (1986), Groot Leiderdop (1985-1987), Groot Utrecht (1987), Groot
Voorschoten (1986-1987), Het Stadsblad (1986-1987), Het Vrije Volk (1986-
1988), Leiderdorps Weekblad (1986), Leids Nieuwsblad (1986), Leidsch Dagblad
(1986-1988), De Leidse Post (1986), Merwekoerier (1986), Merwesteyn (1987),
Nieuwsweek (1985-1988), Oegstgeester Courant (1986-1987), Woensdag
(1987), Zuid-Holland Post (1987), Zuilen (1986-1987). </li>
</ul>

<p><b>Advertising material</b></p>

<ul>
<li>Collection of quotations from advertising leaflets (1985-1986)</li>
</ul>

<p><b>Television news broadcast transcriptions</b></p>

<ul>
<li>NOS Jeugdjournaal (1991-1995)</li>

<li>NOS Journaal (1992-1995)</li>
</ul>

<p><b>Journals</b></p>

<p>The subject matter is diverse, including environment, language,
politics and popular science.</p>

<ul>
<li>Collection of quotations from diverse journals
(1985-1989)</li>

<li>Waddenbulletin
(1991-1996); Waterkampioen (1992-1996); Onze Taal (1991-1995); Liberaal Reveil
(1992-1996); Zenit (1992-1993); Greenpeace (1989-1995); Playboy (1992, 1993,
1995); Rooie vrouwen Magazine (1992-1994)</li>
</ul>

<p><b>Books</b></p>

<ul>
<li>A diverse collection of books (1990-1998). The subject matter
includes linguistics, religion, society and politics.</li>
</ul>

<p class='internal'><b><u>Added to the above mentioned material, only internally available</u></b></p>
<p class='internal'>The ANW corpora, the 50 miljoen woordencorpus, the corpus Ewoud Sanders</p>

<p><b>For the second release the following sources have been added:</b></p>

<p class='internal'><b><u>Also available on chn.inl.nl</u></b></p>
<p><b>Newspapers</b></p>

<ul>
<li>
NRC Handelsblad (July 2013-December 2013); 
De Standaard (July 2013-December 2013);
Antilliaans Dagblad (2012-2013); 
De Ware Tijd (2010, 2012);
Starnews</li> (2008-2013)
</ul>

<p><b>Books</b></p>
<ul>
<li>A diverse collection of books by Surinam writers</li>
</ul>

<p><b>Texts on internet </b></p>

<ul>
<li>Texts on the website of Schrijversgroep '77 (Oktober 2008-August 2011)
Blog of Elodie Heloise (April 2007-February 2014)</li>
</ul>

<p class='internal'><b><u>Added to the above mentioned material, only internally available</u></b></p>
<p class='internal'>The Twente News Corpus, consisting of newspapers, autocues and teletext from the Netherlands. See also http://hmi.ewi.utwente.nl/TwNC.</p>

<h3>Metadata</h2>

<p>For each document to be added to the CHN, the available metadata has been converted into one format. Harmonisation of the content of the metadatacategories is an ongoing process; we hope to improve the information in the future.  We have added to the already available metadata of each document information on the type of information carrier (medium), data witness (for the content of which for this corpus we used publication date) and language variant. Each document has also received a persistent identifier. The available metadata categories are listed below. 

<p>One can <i>view</i> document metadata by clicking on the document title in the per hit or per document result view, or clicking “view document info” in the per document view.</p>
<p>In the current version of the retrieval application, one can now <i>search for</i> or <i>filter by</i> five criteria: title, author, year of publication, medium
and language variety. The possible values for the last criterion are <i>NN</i>
(Dutch from the Netherlands), <i>BN</i> (Dutch from Belgium), <i>SN</i> (Dutch from Suriname) and <i>AN</i> (Dutch from Netherlands Antilles).</p>


 <p><b>Metadata categories</b></p>

<p></p>

<p><b>Bibliographical information</b></p>

<table  >
 <tr>
  <td valign=top >
  <p><i>titleLevel1</i></p>
  </td>
  <td valign=top >
  <p>Title
  of a text or text fragment which has not been not published separately, but
  as part of a larger publication, such as a text (fragment) published in
  an edition, a newspaper article, a poem or short story published in a larger
  collection, etc.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>titleLevel2</i></p>
  </td>
  <td valign=top >
  <p>Title
  of a separately published book, collection, edition etc.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>authorLevel1</i></p>
  </td>
  <td valign=top >
  <p>Author(s)
  of a text or text fragment which has not been not published separately,
  but as part of a larger publication.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>authorLevel2</i></p>
  </td>
  <td valign=top >
  <p>Authors
  of a separately published book, collection, edition etc.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>medium</i></p>
  </td>
  <td valign=top >
  <p>Type of
  information carrier. Possible values are book, newspaper, periodical magazine, periodical local, web snippet, blog, reported speech, written to be spoken, misc website, misc leaflets, misc other.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>newspaperEdition</i></p>
  </td>
  <td valign=top >
  <p>Information
  pertaining to morning vs. evening edition or regional edition of a newspaper</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>pageNumber</i></p>
  </td>
  <td valign=top ></td>
 </tr>
 <tr>
  <td valign=top >
  <i>pubYear_from</i>, 
  <i>pubYear_to</i>, 
  <i>pubMonth_from</i>, 
  <i>pubMonth_to</i>, 
  <i>pubDay_from</i>, 
  <i>pubDay_to</i> 
  </td>
  <td valign=top >
  <p>Year,
  month, day of publication.</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>placePublication</i></p>
  </td>
  <td valign=top >
  <p>Place
  of publication</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>publisher</i></p>
  </td>
  <td valign=top ></td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>editionNumber</i></p>
  </td>
  <td valign=top ></td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>isbn</i></p>
  </td>
  <td valign=top >
  <p>International
  Standard Book Number (ISBN)</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>corpusProvenance</i></p>
  </td>
  <td valign=top >
  <p>Subcorpus
  from which indicates from which existing corpus the tekst originates</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>pid</i></p>
  </td>
  <td valign=top >
  <p>Persistent identifier</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>sourceArticle</i></p>
  </td>
  <td valign=top >
  <p>(for
  newspaper articles) name of press agency</p>
  </td>
 </tr>
</table>

<p><b>Dating of text and text witness</b></p>

<p>These data categories are most relevant for historical text, where
a single text may be handed down to us in the form of “text witnesses” which
are to be dated at large chronological distances from the estimated date of the
creation of the original text. In the current corpus, the values of these
categories do not differ significantly from the publication date.</p>

<p></p>

<table  >
 <tr>
  <td valign=top >
  <i>textYear_from</i>,
  <i>textYear_to</i>,
  <i>textMonth_from</i>,
  <i>textMonth_to</i>,
  <i>textDay_from</i>,
  <i>textDay_to</i>
  </td>
  <td valign=top >
  <p>Date of
  origin of the text</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <i>witnessYear_from</i>,
  <i>witnessYear_to</i>,
  <i>witnessMonth_from</i>,
  <i>witnessMonth_to</i>,
  <i>witnessDay_from</i>,
  <i>witnessDay_to</i>
  </td>
  <td valign=top >
  <p>Date of
  origin of the text witness</p>
  </td>
 </tr>
</table>

<p></p>

<p><b>Text type</b></p>

<p>Please be aware of the fact that these data result from grouping
different sources with different annotation practices (which may in fact have
quite some internal inconsistency as well).</p>

<p></p>

<table  >
 <tr>
  <td valign=top>
  <p><i>articleClass</i></p>
  </td>
  <td valign=top >
  <p>Subject
  matter; section of newspaper devoted to a certain subject, e.g. business,
  society, environment, culture</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>keywords</i></p>
  </td>
  <td valign=top >
  <p>Word or group of words taken out of a title or of a document characterizing its content</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>properties</i></p>
  </td>
  <td valign=top >
  <p>Type of
  article (review, column, etc.)</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>statusText</i></p>
  </td>
  <td valign=top >
  <p>Translated
  or original</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>sourceLanguage</i></p>
  </td>
  <td valign=top >
  <p>Source
  language of translation</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>languageVariant</i></p>
  </td>
  <td valign=top >
  <p><i>NN</i> (Dutch from the Netherlands), <i>BN</i> (Dutch from Belgium), <i>SN</i> (Dutch from Suriname) and <i>AN</i> (Dutch from the Netherlands Antilles)</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>settingLocation</i></p>
  </td>
  <td valign=top >
  <p>Location
  (city, country, region) to which the newspaper article refers</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>settingOrganization</i></p>
  </td>
  <td valign=top >
  <p>Organisation
  (company, sports club, politcal party, etc.) to which the newspaper article
  refers</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>settingPerson</i></p>
  </td>
  <td valign=top >
  <p>Persons
  to which the newspaper article refers</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>newspaperSection
   </i></p>
  </td>
  <td valign=top >
  <p>Newspaper
  section, e.g. Society, Sport, Regional, Business, Film, Front page</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>sectionColumn</i></p>
  </td>
  <td valign=top >
  <p>(for
  repeated pieces or articles) Name of the relevant newspaper column name or
  section</p>
  </td>
 </tr>
</table>

<p></p>

<p><b>Copyright / IPR</b></p>

<p></p>

<table  >
 <tr>
  <td valign=top >
  <p><i>copyrightHolder</i></p>
  </td>
  <td valign=top >
  <p>Person or organization holding the
  copyright, to whom the copyright has been transferred</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>copyrightOwner</i></p>
  </td>
  <td valign=top >
  <p>Person or organization regared as owner
  of the copyright, often the author of the text</p>
  </td>
 </tr>
 <tr>
  <td valign=top >
  <p><i>ipr</i></p>
  </td>
  <td valign=top >
  <p>Intellectual Property Rights</p>
  </td>
 </tr>
</table>

<p><br>
<br>
</p>


<p class='spacer'><a name='help'></a>&nbsp;</p>
<h2>HELP</h2>
    <p>
        Accessing the contents of the <i>Corpus Hedendaags Nederlands</i> can be done via a simple search interface and via CQL. Searching this text material is possible because of the linguistic annotation with Part of Speech and Modern Lemma of each word in the text.
    </p>
    <h3>Simple Search</h3>
    <p>
        You can search for words matching one or more of the three properties: WORD FORM, LEMMA and  PART OF SPEECH. Use the search boxes on the top left of the website&#39;s home page.
    </p>
    <p>
        A <b>word form</b> is an occurrence of a word in the text.  By typing <i>wandelen</i> ('collection') in the word form search box, you will find the occurrences of <i>wandelen</i> in the collection.
    </p>
    <p>
        <i>Wandelen</i> is only one of the possible forms for <i>"wandelen"</i>. You can search for all forms by looking for the <b>lemma</b> <i>wandelen</i>, using the lemma search box. 
    </p>
    <p>
        It is also possible to search for words with a specific <b>Part of Speech</b> in the text. For example if you want to know which <i>adjectives</i> were used in the text, search for <i>AA*</i> in the <b>Part of Speech</b> search field.
    </p>
    <p>
        Combining features is possible when searching. If you are looking for the lemma <i>leven</i> as a verb ('to live'), type <i>leven</i> in the <b>Lemma search box</b> and <i>VRB*</i> in the <b>Part of Speech search box</b>. You will find all instances of the verb <i>leven</i>. For the occurences of the noun "leven", enter <i>NOU.*</i> in the part of speech box.
    </p>
    <p>
        Searching with a <b>* wildcard</b> is also possible. For example, in order to search for all words containing <i>lopen</i> ('walk'), you can do that by typing <i>*lopen*</i> in the lemma search box. Wildcard search is supported for WORDFORM, LEMMA and PART OF SPEECH searches. The <b>*</b> (asterisk) symbol matches <i>zero or more</i> characters.
    </p>
    <p>
        Searching for a <b>word group</b> is also possible by simply typing the word group in the search box. Typing <i>lief man</i> ('sweet husband/man') in the lemma search box will give you all occurrences of words with the lemma <i>lief</i> immediately followed by words with the lemma <i>man</i>. If you want to search for the combination <i>het leven</i> ('the life') where 'leven' is a noun, type the string <i>het leven</i> in the <b>lemma search box</b> and <i>PD* N*</i>  in the <b>Part of Speech search box</b>.
    </p>
    <p>
        The part of speech tagset is documented in the INL working paper <a href="http://www.inl.nl/images/stories/onderzoek_en_onderwijs/publicaties/TaalbankWorkingpaper3.pdf">De 
morfosyntactische 
module van het 
GiGaNT-lexicon</a>. 
        The list of main Part of Speech tags is:
        <ul>
        <li>AA*: adjective or adverb</li>
        <li>ADP*: preposition</li>
            <li>ADV*: adverb</li>
            <li>CONJ*: conjunction</li>
            <li>INT: interjection</li>
            <li>NOU-C*: common noun</li>
            <li>NOU-P*: common noun</li>
            <li>NUM: numeral</li>
            <li>PD*: pronoun, determiner, article</li>
            <li>RES*: residual categories (abbreviation, formula, symbol, truncated word, unknown)</li>
            <li>VRB*: verb</li>
            </ul>
        Search can be performed by clicking on SEARCH in the window or using ENTER on your keyboard. By clicking on RESET, all selections or information in search boxes will be cleared.
    </p>
    <h3>Filtering by metadata</h3>
    <p>
        All the above mentioned searches are performed on the complete corpus. If you want to search in a particular subset of the material, you can do that by using the metadata information accompanying each text in the collection.
    </p>
    <p>
        You can search by AUTHOR, TITLE, PUBLICATION YEAR and LANGUAGE VARIANT.
    </p>
    <p>
        To find texts from a specific time period, fill in "year from" and "year to". To find texts starting from a specific year, fill in "year from". To find text from a specific year, fill in that year in both "year from" and "year to" 
    </p>
    <p>
        To restrict your search to texts from either the Netherlands of from Belgium, use the Language variant dropdown list.
    </p>
    <h3>Search results</h3>
    Search results can be presented in four different ways: Per hit, Per document, Hits Grouped, Documents Grouped.
    <h4>Per Hit</h4>
    <p>
        Here the search results are presented in the form of concordances, an overview of every occurrence of the query word with x words of surrounding context. The word that is searched for (the hit), is shown in bold type and supplied with information on its lemma and part of speech.
    </p>
    <p>
        The number of concordances per page can be determined by choosing the number from the drop-down list after SHOW ME. The number of pages that can be displayed are presented above the concordances. By clicking on a number or on NEXT you can see the results of another page.
    </p>
    <p>
        To view the concordances with or without metadata, click on SHOW/HIDE TITLES.
    </p>
    <p>
        Clicking on a title is the way to view the complete document metadata. 
    </p>
    <p>
        By clicking on a concordance line, more context is presented.
    </p>
    <p>
        There are several ways in which you can change the order of the concordances.
    </p>
    <p>
        By clicking on LEFT CONTEXT and choosing "word" the concordances are sorted by ordering the word to the left of the hit text alphabetically. You can do the same for RIGHT CONTEXT. By clicking on HIT TEXT or LEMMA or PART OF SPEECH, Hits or Lemmas or PoS's are presented in alphabetical order. To go from ascending to descending alphabetical order or vice versa, simply click on the chosen item again.
    </p>
    <h4>Per Document</h4>
    <p>
        To have a better overview of the documents in which your search was successful, switch to the per-document view by clicking on PER DOCUMENT.
    </p>
    <p>
        The documents are listed, with one example accompanied by information on the date of the document and the total number of occurrences of the hit text in the document.
    </p>
    <p>
        The document metadata can be viewed by either clicking on the title or on VIEW DOCUMENT.
    </p>
    <p>
        There are several ways in which you can change the order of the documents.
    </p>
    <p>
        By clicking on DOCUMENT TITLE, the information is presented in alphabetical order. To go from ascending to descending alphabetical order or vice versa, simply click on DOCUMENT TITLE again.
    </p>
    <p>
        By clicking on YEAR, the documents are presented in chronological order. To go from chronological order to reverse chronological order and vice versa, simply click on YEAR again.
    </p>
    <p>
        By clicking on HITS, the documents are ordered by frequency. To go from low to high frequency or vice versa, simply click on HITS again.
    </p>
    <h4>Hits Grouped</h4>
    <p>
        In this view the search result can be grouped in different ways, all related to the hit text, which makes a first analysis of the search results easier. To use this view, click on HITS GROUPED. Then select in the drop down list the feature by which you want to group your search results. This can be <i>document title, hit text, lemma, hit PoS, lemma and PoS, word left, word right</i> or <i>year</i>. For instance, grouping the results of the lemma query <em>vrouw</em> ('wife') <em>by hit text</em> will display the frequency of occurrence of each word form in the paradigm of the lemma.
    </p>
    <p>
        It is possible to see concordances of one group in the overview by clicking on the green bar with the frequency number. In the concordance view that appears, you can get more concordances in the same view by clicking on LOAD MORE CONCORDANCES. To restore the original view without concordances, click on the same green bar again. It is possible to get a more detailed view of the concordances in a group, by clicking on VIEW DETAILED CONCORDANCES IN THIS GROUP. However, to change from the detailed concordances view back to the per-hit view, the search has to be repeated.
    </p>
    <h4>Documents Grouped</h4>
    <p>
        This view is similar to "Hits grouped" but now the data is grouped in different ways, all related to information on the document. To use this view, click on DOCUMENTS GROUPED. Then select in the drop-down list the feature by which you want to group your search results. This can be <i>number of hits, by year and by author</i>. <i>Number of hits</i> gives the number of documents per frequency of hits in a document of your search result, <i>by year</i> gives the number of documents per year in your search result, <i>by author</i> gives the number of documents per author in your search result.
    </p>
    <p>
        To see the documents per overview, do the same as described in "Hits grouped", be it that now you see an orange bar. By clicking on the orange bar, you get an overview of the document titles that match.
    </p>
    <h3>CQL query</h3>
    <h4>Corpus Query Language</h4>
    <p>Click on the tab "CQL query"  to use the Corpus Query Language. This is an advanced query language developed at IMS, University of Stuttgart in the early 1990s, designed to support very specific retrieval of phrase types in the corpus. It expresses phrase queries as sequences of token queries. It is therefore mainly useful if you want to find specific types of phrases in a larger text. An example of a simple query (note that the quotes are required): <code>"grote" ".*heid"</code>.</p>
    <p>This is how you search for the word "grote" followed by a word ending with "heid", using regular expressions to specify the pattern for the second word. Equivalent to the above query is: <code>[word="grote"] [word=".*heid"]</code> which has the typical form of a CQL query: a phrase query built up from token queries surrounded by square brackets.</p>
    <h4>Single token queries</h4>
    <p>These typically consist of a combination of simple attribute value queries in the form of either:
    <ul>
        <li>token attribute=single token regular expression <code>[word=".*heid"]</code> surrounded by square brackets</li>
        <li>default token attribute regular expression <code>".*heid"</code></li>
    </ul>
    </p>
    <p>In this corpus, the following token attributes are available for querying:
    <ul>
        <li>word - The word as it was written. This is the default attribute in this corpus, so querying by only giving a word between brackets, eg. "man" means asking for [word="man].</li>
        <li>lemma - Dictionary headword form of words</li>
        <li>pos - Part of speech</li>
    </ul>
    </p>
    <p>
    A typical example using all three token attributes: <code>[pos="AA.*"] [lemma="man" & word != "man"]</code>. This is how you search for adjectives followed by an occurrence of the lemma "man", which may or may not be the form 'man' itself.
    </p>
    <h4>Phrase queries</h4>
    <p>
    As you have seen, phrase queries can simply consist of a sequence of single token queries. Apart from this, regular expression  notations are available to express sequences of tokens. For example: <code>"der.*"{2,}</code>. This query finds two or more successive words starting with "der". At the token level, regular expression operators such as *, + and ? are available. Another example: <code>[pos="AA.*"]+ "man"</code>. This will find the word "man" with one or more adjectives applied to it. 
    </p>
    <h4>Summary of Corpus Query Language support</h4>
    <p>
        The following CQL constructs are supported:
        <ul>
            <li>
            Token constraints of the form [word="koe"] or "koe" (default property). Constraint values may be regular expressions, e.g. [word="str.+"] . The regular expression operators are:
            <ul>
                <li><code>.</code> (full stop) matches arbitrary character: b.k finds bok, bak, bek, bik, etc.. </li>
                <li><code>*</code> matches zero or more occurrences of the preceding letter or bracketed group: .*schip finds words ending with schip (also matching "schip"), dia.* finds words beginning with dia, .*deel.* finds words with deel in the middle.</li>
                <li><code>+</code> matches 1 or more occurrences of the preceding letter or bracketed group: .+schip finds words ending with schip (not matching "schip")</li>
                <li><code>{n,m}</code> matches a sequence of n to m occurrences of preceding letter or group. Use {n} to find a sequence of length n, {n,}  to find at least n, {0,n} to find at most n: <code>[word=".*[aeiou]{5,6}.*"]</code> finds words containing a group of 5 or 6 vowels</li>
                <li><code>?</code> The bracketed items are optional characters: blond(e)? finds blond and blonde </li>
                <li><code>|</code> Vertical bar (disjunction): paard|koe|schaap  searches for all of these items</li>
                <li><code>[]</code> Square brackets (character groups): b[ae]k finds bak, bek</li>
                <li><code>\</code> To search for a full stop, use the backslash and the full stop: Dr\. finds Dr.</li>
            </ul>
            </li>
            <li>
                Constraints may be combined by using boolean operators, both between token specifications (e.g. "stad" | "dorp" ) and within token specifications (e.g. [lemma="zijn" & pos="VRB.*"] ). Supported boolean operators are ! (not), & (and) and | (or). Implication (->) is not supported yet. Parentheses may be used to group expressions. 
            </li>
            <li>Phrase searches, by putting several token specifications in sequence, e.g.: "de" [lemma="koe"] </li>
            <li>You can apply regular expression operators (* + ? {a,b}) to token specifications, e.g.: [type="VRB.*"]+ (one or more verbs) or "k.*"{3,} (three or more words starting with k) </li>
            <li>You can use match all tokens ([]) to match any word, e.g. "koe" []{1,2} "schaap" to find "koe" and "schaap" in that order with 1-2 words between them. </li>
            <li>You can search for XML tags (in the current version the only indexed tag is  &lt;s/&gt;, sentence) in the following ways: &lt;s&gt; "Gelukkig" (word at start of sentence), "gelukkig" &lt;/s&gt; (word at end of sentence). </li>
        </ul>
    </p>
    
<p class='spacer'><a name='beta'></a>&nbsp;</p>
    <h2>BETA</h2>
<p>This is a BETA release of the <i>Corpus Hedendaags Nederlands</i>. The search application gives access to prior and new corpus material of the INL. Development is still ongoing, so your <a href="mailto:servicedesk@inl.nl">feedback</a> is more than welcome.</p>
<p>Envisaged for the coming period, apart from regular updates of the newspaper material, is improvement of the back end technology (performance), extension of the metadata search and improvements of the user interface.</p>
<p class='endspacer'><a name='end'></a>&nbsp;</p>

<script>if (location.href.toLowerCase().indexOf('chn-i') >= 0) $('.internal').show();</script>
