<h2>Help</h2>
Welcome to the Corpus Gysseling search. You can search the contents of Corpus Gysseling for words matching one or more of the four properties: lemma, POS, word form and POS gysseling. The following rules apply:
<ul>
<li>If you leave a search field empty it will not be included in the search.</li>
<li>You can specify the search type using the dropdown boxes left of the search fields.</li>
<li>A (lemma) search for <i>gaan staan</i> is interpreted as the word <i>gaan</i> immediately followed by the word <i>staan</i>.</li>
<li>A lemma search for <i>paard</i>  includes all clitics by keying in: <i>*+paard or paard or paard+*</i>.</li>
<li>You can combine different search terms of the same type by the keyword <i>OR</i> (case sensitive). A lemma search for <i>koe OR huis</i> is interpreted as a search for words for which the lemma equals <i>koe</i> or <i>huis</i>.</li>
<li>You can combine the different search fields using the boolean AND or OR operators in the dropdown boxes.</li>
<li>All boolean OR operators are interpreted as <i>inclusive OR</i>.</li>
<li>You can specify a wildcard search using the asterix (<i>*</i>). For example you can find all nouns by searching for <i>NOU*</i> in POS. Wildcard search can be used on all search fields.</li> 
<li>You can limit your search to specific authors, sources or time periods using the <i>Limit search to</i> options below.</li>
<li>You can adjust the amount of results per page using the dropdown box under <i>Limit search to</i>.</li>
<li>You can see the full contents of each document, including the highlighted hits, by clicking the document title in the search results.</li>
<li>You can use the following terms to search on POS:</li>
<ul>
<li>VRB : verb</li>
<li>NOU: noun</li>
<li>ADJ: adjective</li>
<li>ADV: adverb</li>
<li>NUM: numeral</li>
<li>PD: pronoun/determiner</li>
<li>PD(type = art): article</li>
<li>ADP: preposition</li>
<li>CONJ: conjuction</li>
<li>INT: interjection</li>
<li>RES: residual</li>
</ul>
